name: Daily MTG Card Check

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Fetch and process card data
      run: go run cmd/fetcher/main.go
    
    - name: Generate HTML
      run: go run cmd/renderer/main.go data/history.json
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add data/history.json
          git add docs/index.html
          git commit -m "Update card data - $(date -u +%Y-%m-%d)"
          git push
        else
          echo "No changes to commit"
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2